Metrics/AbcSize:
  Max: 18

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Metrics/LineLength:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
  Max: 90
